watcher:
    image: golang
    environment:
        GOPATH: /usr/src/watcher
        CONFIG_PATH: /usr/src/watcher/src/marmelab.com/uptime/url.json
    volumes:
        - .:/usr/src/watcher
    command: sleep 123551588 #go run /usr/src/watcher/src/marmelab.com/uptime/main.go
    links:
        - "api"

api:
    image: golang
    environment:
        GOPATH: /usr/src/api
    volumes:
        - .:/usr/src/api
    command: sleep 15236448 #go run /usr/src/api/src/marmelab.com/uptime/api/api.go
    ports:
        - "8000:80"
    links:
        - "db"


testingsite:
    image: nginx
    ports:
        - "8181:81"
    volumes:
        - ./nginxContainer/static-html-directory:/usr/share/nginx/html

db:
    image: postgres
    ports:
        - "5432:5432"
