watcher:
    image: golang
    environment:
        GOPATH: /usr/src/watcher
        CONFIG_PATH: /usr/src/watcher/src/marmelab.com/uptime/conf.json
    volumes:
        - .:/usr/src/watcher
    working_dir: /usr/src/watcher/src/marmelab.com/uptime
    command: go run main.go
    links:
        - "api"
        - "website"
api:
    image: golang
    environment:
        GOPATH: /usr/src/api
    volumes:
        - .:/usr/src/api
    working_dir: /usr/src/api/src/marmelab.com/uptime/api
    command: go run main.go
    ports:
        - "8383:8383"
    links:
        - "db"

website:
    image: nginx
    ports:
        - "8282:82"
    volumes:
        - ./nginxContainer/static-html-directory:/usr/share/nginx/html

db:
    image: postgres
    volumes:
        - .:/usr/src/db

webpack:
    image: iojs:1.6.3
    working_dir: /usr/src/webpack/front
    volumes:
        - .:/usr/src/webpack
    working_dir: /usr/src/webpack/front
    command: ./node_modules/.bin/webpack-dev-server --progress --hot --host=0.0.0.0
    ports:
        - "8080:8080"
