nginx:
    image: nginx
    ports:
        - "8000:80"
    volumes:
        - ./public:/usr/share/nginx/html
watcher:
    image: golang
    working_dir: /usr/src/watcher
    volumes:
        - .:/usr/src/watcher
    command: sleep 10000
    links:
        - nginx:nginx
