watcher:
    image: golang
    environment:
        GOPATH: /usr/src/watcher
        CONFIG_PATH: /usr/src/watcher/src/marmelab.com/uptime/conf.json
    volumes:
        - .:/usr/src/watcher
    command: go run /usr/src/watcher/src/marmelab.com/uptime/main.go
    links:
        - "api"
        - "site"

api:
    image: golang
    environment:
        GOPATH: /usr/src/api
    volumes:
        - .:/usr/src/api
    command: go run /usr/src/api/src/marmelab.com/uptime/api/api.go
    ports:
        - "8080:8000"
    links:
        - "db"
        - "client"

site:
    image: nginx
    ports:
        - "8181:81"
    volumes:
        - ./nginxContainer/static-html-directory:/usr/share/nginx/html

db:
    image: postgres
    volumes:
        - .:/usr/src/db

webpack:
    image: iojs:1.6.3
    volumes:
        - .:/usr/src/webpack
    command: sleep 1234567 #/usr/src/webpack/front/node_modules/.bin/webpack
    ports:
        - "8888:88"
        - "8080:8080"

client:
    image: iojs:1.6.3
    ports:
        - "8000:8000"
    volumes:
        - ./front:/usr/src/client
    command: node server.js 
