watcher:
    image: golang
    environment:
        GOPATH: /usr/src/watcher
        CONFIG_PATH: /usr/src/watcher/src/marmelab.com/uptime/url.json
    volumes:
        - .:/usr/src/watcher
    command:  go run /usr/src/watcher/src/marmelab.com/uptime/main.go

testingsite:
    image: nginx
    ports:
        - "8000:80"
    volumes:
        - ./nginxContainer/static-html-directory:/usr/share/nginx/html
